server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product-service-route
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**
        - id: review-service-route
          uri: lb://REVIEW-SERVICE
          predicates:
            - Path=/api/reviews/**
        - id: cart-service-route
          uri: lb://CART-DETAIL-SERVICE
          predicates:
            - Path=/api/cart-detail/**
        - id: order-service-route
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**
        - id: payment-service-route
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/api/payments/**
        - id: voucher-service-route
          uri: lb://VOUCHER-SERVICE
          predicates:
            - Path=/api/vouchers/**
        - id: printer-service-route
          uri: lb://PRINTER-SERVICE
          predicates:
            - Path=/api/print-order/**

logging:
  level:
    root: INFO
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "demo"
    description: "Demo keycloak"
    version: "1.0.0"
      
cors:
  allowed-origins:
    - http://localhost:8080
    - "*"
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      productCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 5
        registerHealthIndicator: true
        allowHealthIndicatorToFail: true
